name: test
run-name: ${{ github.actor }} is running the test
on:
  push:
    tags:
      - 'rc-[0-9]+.[0-9]+.[0-9]+'
jobs:
  test:
    uses: ./.github/workflows/test.yml
  build:
    needs: test
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.6.0'
        cache: 'npm'
    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: |
          dist
    - run: npm install
    - run: npm run build
    - run: sh ./.github/scripts/commits.sh
    - run: node ./.github/scripts/reporter.js ${{ github.actor }}

  prepare_docker_image:
    name: docker
    needs: build
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "prepare docker"

