name: test
run-name: ${{ github.actor }} is running the test
on:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '16.6.0'
        cache: 'npm'
    - uses: actions/checkout@v3
    - run: npm —Åi
    - run: npm ts
    - name: linter
      if: ${{ success() }}
      run: npm run lint
